// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package httpserver

import (
	"github.com/google/wire"
	"github.com/kangyueyue/template/internal/httpserver/hello"
)

// Injectors from wire.go:

// InitialHttpServer 初始化服务
func InitialHttpServer() *Server {
	helloSvr := hello.NewHelloSvr()
	server := NewServer(helloSvr)
	return server
}

// wire.go:

var SvrSet = wire.NewSet(hello.NewHelloSvr)
